using './main.bicep'

param vmName = 'vm-test-${readEnvironmentVariable('buildId', '001')}'
param adminUsername = 'adminUserName'
param authenticationType = 'password'
param dnsLabelPrefix = 'dns-label-prefix-${readEnvironmentVariable('buildId', '001')}'
param ubuntuOSVersion = '18.04-LTS'
param vmSize = 'Standard_B2s'
param virtualNetworkName = 'vNet'
param subnetName = 'Subnet'
param networkSecurityGroupName = 'SecGroupNet'
param location = 'westus'
