using './main.bicep'

param serviceName = 'apim-test-${readEnvironmentVariable('buildId', '001')}'
param location = 'westus'
param apiName = 'api-test'
param workspaceName = 'logworkspace-test'
param appInsightsName = 'appinsights-test'
param loggerName = 'log-test'
param diagnosticName = 'applicationinsights'
param policyName = 'policy'
