trigger: none

pool: default

parameters:
  - name: location
    default: "westus"

  - name: subscriptionId

  - name: resourceGroupName
    default: "rg-enpolat-$(Build.BuildNumber)"

  - name: runNumber
    default: $(Build.BuildNumber)

variables:
  - name: serviceConnectionName
    value: "sc_arm"

jobs:

- job:
  displayName: 'Deploy'

  steps:

  - task: AzureCLI@2
    displayName: Az CLI Deploy Resource Group
    name: deploy_resource_group
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(subscriptionId)
        az account show
