trigger: none

pool: "Azure Pipelines"

variables:
  - name: serviceConnectionName
    value: "sc_arm"

  - name: location
    value: "westus"

  - name: resourceGroupName
    value: "rg-enpolat-$(Build.BuildNumber)"

  - name: runNumber
    value: $(Build.BuildNumber)

jobs:

- job:
  displayName: 'Deploy and Test Bicep Modules'

  steps:

  - task: AzureCLI@2
    displayName: Setup
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az bicep install
        az bicep upgrade
        write-Host resourceGroupName: $(resourceGroupName)
        write-Host runNumber: $(runNumber)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Resource Group
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        foreach ($module in Get-ChildItem -Path "./bicep/modules" -Directory) {
          $modulePath = $module.FullName
          Write-Host "Processing module: ${modulePath}"

          # Example: az bicep build and deploy commands
          az bicep build --file "$modulePath/main.bicep" --outdir "$modulePath"

          # az deployment group create --resource-group MyResourceGroup --template-file "$modulePath/out/main.json" --parameters "$modulePath/out/main.parameters.json"
        }
