trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  serviceConnectionName: "sc_arm"
  location: "westus"
  subscriptionId: ""
  resourceGroupName: "rg-enpolat-$(Build.BuildNumber)"
  runNumber: $(Build.BuildNumber)

jobs:
- job:
  displayName: 'Deploy'
  steps:
  - task: AzureCLI@2
    displayName: Az CLI Deploy Resource Group
    name: deploy_resource_group
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(subscriptionId)
        az account show
