trigger: none

pool: "Azure Pipelines"

variables:
  - group: "BenchPress"

  - name: serviceConnectionName
    value: "sc_arm"

  - name: location
    value: "westus"

  - name: buildId
    value: "$(Build.BuildId)"

  - name: resourceGroupName
    value: "rg-enpolat-$(Build.BuildId)"

jobs:

- job:
  displayName: "Deploy and Test Bicep Modules"
  timeoutInMinutes: 120

  steps:

  - task: AzureCLI@2
    displayName: "Setup"
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        az bicep install
        az bicep upgrade

  - task: AzureCLI@2
    displayName: "Troubleshooting"
    env:
      buildId: $(buildId)
      AZ_SP_HAWAII: $(AZ_SP_HAWAII)
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        Write-Host "BuildId: $(buildId)"
        Write-Host "Creating resource group: $(resourceGroupName)"
        Write-Host "BenchPress: $(BenchPress)"
        Write-Host "AZ_APPLICATION_ID 0: $(AZ_APPLICATION_ID)"
        Write-Host "AZ_APPLICATION_ID 1: $(BenchPress.AZ_APPLICATION_ID)"
        Write-Host "AZ_SP_APP_ID: $(AZ_SP_APP_ID)"
        Write-Host "AZ_SP_HAWAII: $(AZ_SP_HAWAII)"

  - task: AzureCLI@2
    displayName: "Deploy Resource Group"
    env:
      buildId: $(buildId)
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        Write-Host "BuildId: $(buildId)"
        Write-Host "Creating resource group: $(resourceGroupName)"

        az group create --name $(resourceGroupName) --location $(location) --output none
        Write-Host "Resource group created: $(resourceGroupName)"

        foreach ($module in Get-ChildItem -Path "./bicep/modules" -Directory) {
          $modulePath = $module.FullName

          Write-Host "Processing module: ${modulePath}"
          az deployment group create --resource-group $(resourceGroupName) --template-file "$modulePath/main.bicep" --parameters "$modulePath/parameters.bicepparam" --output none
          Write-Host "Module deployed: ${modulePath}"
        }

  - task: AzureCLI@2
    displayName: "Run e2e tests"
    env:
      buildId: $(buildId)
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      workingDirectory: '$(Build.SourcesDirectory)/bicep/tests'
      inlineScript: |
        Invoke-Pester -OutputFile test.xml -OutputFormat NUnitXML
